apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: es-single
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      name: es-single
      labels:
        app: es-single
    spec:
      terminationGracePeriodSeconds: 90
      initContainers:
      # init-container for setting the mmap count limit
      - name: sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      #- image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
      - name: es-single
        image: 10.10.56.148:5000/elasticsearch:6.4.0
        env:
        - name: network.host
          value: "_site_"
        - name: node.name
          #value: "${HOSTNAME}"
          value: "cbov10-sso55-113"
        - name: discovery.zen.ping.unicast.hosts
          #value: "${ES_SINGLE_NODEPORT_SERVICE_HOST}"
          value: "10.10.55.113"
        - name: cluster.name
          value: "test-single"
        - name: ES_JAVA_OPTS
          value: "-Xms1024m -Xmx1024m"
        volumeMounts:
        - name: es-single-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-single-data
          emptyDir: {}
