apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kb-single
  namespace: elk
spec:
  replicas: 1
  template:
    metadata:
      name: kb-single
      labels:
        app: kb-single
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: kb-single
      #- image: docker.elastic.co/kibana/kibana:6.4.0
        #name: kb
        image: 10.10.56.148:5000/kibana:6.4.0
        env:
        #- name: ELASTICSEARCH_URL
        - name: "ELASTICSEARCH_URL"
          #value: "http://es-single:9200"
          value: "http://10.10.55.113:31200"
        ports:
        - name: http
          containerPort: 5601
