apiVersion: v1
kind: Service
metadata:
  name: kb-single-svc
  namespace: elk
spec:
  type: NodePort
  ports:
  - name: http
    port: 5601
    targetPort: 5601 
    nodePort: 32601
  selector:
    app: kb-single  
